blogs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from blogs.apps import BlogsConfig
from blogs.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView, main

app_name = BlogsConfig.name

urlpatterns = [
    path('', main, name='main'),
    path('blogs/', BlogListView.as_view(), name='blogs'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls', namespace='blogs')),
    path('users/', include('users.urls', namespace='users')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('client/', include('client.urls', namespace='client'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from mailing.apps import MailingConfig
from mailing.views import MailingListView, MailingDetailView, MailingCreateView, \
    MailingUpdateView, MailingDeleteView


app_name = MailingConfig.name

urlpatterns = [
    path('list/', MailingListView.as_view(), name='list'),
    path('view/<int:pk>', MailingDetailView.as_view(), name='view_mailing'),
    path('create/', MailingCreateView.as_view(), name='create'),
    path('edit/<int:pk>', MailingUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', MailingDeleteView.as_view(), name='delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

from blogs.models import NULLABLE
from client.models import Client


class Message(models.Model):
    """
    Модель Сообщения
    """

    theme = models.CharField(max_length=150, verbose_name='Тема сообщения')
    body = models.TextField(verbose_name='Текст сообщения')
    created_at = models.DateField(**NULLABLE, auto_now_add=True, verbose_name="Дата создания")
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Пользователь', on_delete=models.CASCADE,
                              **NULLABLE)

    def __str__(self):
        return f"{self.theme}"

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = 'Сообщения'


class Mailing(models.Model):
    """
    Модель Рассылки
    """

    TITLE_CHOICES_PERIODICITY = [
        (1, 'Раз в день'),
        (2, 'Раз в неделю',),
        (3, 'Раз в месяц',),
    ]

    TITLE_CHOICES_STATUS = [
        (1, 'Создана'),
        (2, 'Запущена',),
        (3, 'Завершена',),
    ]

    mailing_time = models.DateTimeField(verbose_name="Время рассылки", default=timezone.now)
    period = models.PositiveSmallIntegerField(verbose_name="Периодичность",
                                              choices=TITLE_CHOICES_PERIODICITY, default=1)
    status = models.PositiveSmallIntegerField(verbose_name='Статус рассылки',
                                              choices=TITLE_CHOICES_STATUS, default=1)
    message = models.ForeignKey(Message, on_delete=models.SET_NULL, **NULLABLE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Пользователь',
                              on_delete=models.CASCADE, **NULLABLE)
    clients = models.ManyToManyField(Client, verbose_name='Клиенты')

    def __str__(self):
        return f"{self.status}"

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'

        permissions = [("set_inactive", "Can block mailing")]


class Log(models.Model):

    date_attempt = models.DateTimeField(verbose_name='Дата попытки')
    status = models.CharField(max_length=150, verbose_name='Статус попытки')
    answer = models.TextField(**NULLABLE, verbose_name='Ответ сервера')
    mailing = models.ForeignKey(Mailing, **NULLABLE, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.status} {self.date_attempt}"

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

mailing/forms.py
from django import forms

from blogs.forms import StyleFormMixin
from mailing.models import Mailing, Message


class MailingForms(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Mailing
        exclude = ['owner']


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        exclude = ("owner",)

mailing/views.py
import typing
from django.conf import settings

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.cache import cache

from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from mailing.forms import MailingForms
from mailing.models import Mailing, Log


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing
    template_name = 'mailing/mailing_list.html'

    def get_queryset(self):
        return super().get_queryset().filter(owner=self.request.user)


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing
    template_name = 'mailing/mailing_detail.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if settings.CACHE_ENABLED:
            key = f'log_list_{self.object.pk}'
            log_list = cache.get(key)
            if log_list is None:
                log_list = self.object.log_set.all()
                cache.set(key, log_list)
        else:
            log_list = self.object.log_set.all()
        context_data['logs'] = log_list

        return context_data


class MailingCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForms
    permission_required = 'mailing.add_mailing'
    success_url = reverse_lazy('mailing:list')

    def form_valid(self, form: typing.Any) -> typing.Any:
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForms
    permission_required = 'mailing.change_mailing'
    success_url = reverse_lazy('mailing:list')


class MailingDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Mailing
    permission_required = 'mailing.delete_mailing'
    success_url = reverse_lazy('mailing:list')

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'blogs/base.html'%}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить рассылку?</p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <a href="{% url 'mailing:list'%}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'blogs/base.html'%}
{% block content %}
<div class="col-12 mb-5">
<a class="btn btn-outline-primary" href="{% url 'blogs:main'%}">Назад</a>
</div>
<div class="col-md-6">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">{{ object.mailing_time }}</p>
            <p class="card-text">{{ object.get_period_display }}</p>
            <p class="card-text">
                {% if object.status == 3 %}
                    <span class="text-muted">{{ object.get_status_display }}</span>
                {% else %}
                    {{ object.get_status_display }}
                {% endif %}
            </p>
        </div>
    </div>
</div>
<div class="col-md-6">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <div class="card-title">
                Отчет по отправке
            </div>
        </div>
        <div class="card-body">
            {% for log in logs %}
                <p class="card-text">{{ log.date_attempt }} {{ log.status }} {{ log.answer }}</p>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'blogs/base.html'%}
{% block content %}
<div class="col-12 mb-5">
<a class="btn btn-outline-primary" href="{% url 'blogs:main' %}">Назад</a>
</div>
<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Добавление рассылки
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'blogs/base.html'%}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'mailing:create'%}">Добавить рассылку</a>
    <a class="btn btn-outline-primary" href="{% url 'blogs:main'%}">Назад</a>
</div>
{% for object in object_list %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">{{ object.mailing_time }}</p>
            <p class="card-text">{{ object.get_period_display }}</p>
            <p class="card-text">
                {% if object.status == 3 %}
                    <span class="text-muted">{{ object.get_status_display }}</span>
                {% else %}
                    {{ object.get_status_display }}
                {% endif %}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    {% if perms.mailing.view_mailing %}
                        <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'mailing:view_mailing' object.pk %}">Просмотр</a></button>
                    {% endif %}
                    {% if perms.mailing.change_mailing %}
                        <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'mailing:edit' object.pk %}">Редактировать</a></button>
                    {% endif %}
                    {% if perms.mailing.delete_mailing %}
                        <button type="button" class="btn btn-sm btn-outline-danger"><a href="{% url 'mailing:delete' object.pk %}">Удалить</a></button>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}