blogs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from blogs.apps import BlogsConfig
from blogs.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView, main

app_name = BlogsConfig.name

urlpatterns = [
    path('', main, name='main'),
    path('blogs/', BlogListView.as_view(), name='blogs'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from client.apps import ClientConfig
from client.views import ClientListView, ClientCreateView, ClientUpdateView, ClientDetailView, ClientDeleteView

app_name = ClientConfig.name

urlpatterns = [
    path('', cache_page(60)(ClientListView.as_view()), name='client_list'),
    path('create/', ClientCreateView.as_view(), name='create'),
    path('edit/<int:pk>', ClientUpdateView.as_view(), name='edit'),
    path('view/<int:pk>', ClientDetailView.as_view(), name='view_client'),
    path('delete/<int:pk>', ClientDeleteView.as_view(), name='delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls', namespace='blogs')),
    path('users/', include('users.urls', namespace='users')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('client/', include('client.urls', namespace='client'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client/models.py
from django.conf import settings
from django.db import models

from blogs.models import NULLABLE


class Client(models.Model):

    first_name = models.CharField(max_length=100, verbose_name='Имя')
    last_name = models.CharField(max_length=100, verbose_name='Фамилия')
    email = models.EmailField(max_length=100, verbose_name='Почта')
    comment = models.TextField(**NULLABLE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Пользователь',
                              on_delete=models.CASCADE, **NULLABLE)
    is_active = models.BooleanField(default=True, **NULLABLE, verbose_name='Активность')

    def __str__(self):
        return f"{self.last_name} {self.first_name}"

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

client/forms.py
from django import forms

from blogs.forms import StyleFormMixin
from client.models import Client


class ClientForms(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Client
        fields = ("owner",)

client/views.py
import typing

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from client.forms import ClientForms
from client.models import Client


class ClientListView(LoginRequiredMixin, ListView):
    """Контроллер для просмотра сущностей"""
    model = Client
    template_name = 'client/client_list.html'

    def get_queryset(self):
        return super().get_queryset().filter(owner=self.request.user)


class ClientDetailView(DetailView):
    """Контроллер для просмотра сущности"""
    model = Client
    template_name = 'client/client_detail.html'


class ClientCreateView(LoginRequiredMixin, CreateView):
    """Контроллер для создания сущности"""
    model = Client
    form_class = ClientForms
    success_url = reverse_lazy('client:client_list')

    def form_valid(self, form: typing.Any) -> typing.Any:
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    """Контроллер для изменения сущности"""
    model = Client
    form_class = ClientForms
    success_url = reverse_lazy('client:list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404("Доступ запрещен")
        return self.object


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    """Контроллер для удаления сущности"""
    model = Client
    success_url = reverse_lazy('client:client_list')

client/templates/client/client_confirm_delete.html
{% extends 'blogs/base.html'%}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить пользователя?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'client:client_list'%}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

client/templates/client/client_detail.html
{% extends 'blogs/base.html'%}
{% block content %}
<div class="col-12 mb-5">
<a class="btn btn-outline-primary" href="{% url 'client:client_list'%}">Назад</a>
</div>
<div class="col-md-6">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">{{ object }}</p>
            <p class="card-text">{{ object.email }}</p>
            <p class="card-text">{{ object.comment }}</p>
            {% if object.is_active %}
                <p class="card-text">Активен</p>
            {% else %}
                <p class="card-text">Не активен</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

client/templates/client/client_form.html
{% extends 'blogs/base.html'%}
{% block content %}
<div class="col-12 mb-5">
<a class="btn btn-outline-primary" href="{% url 'client:client_list'%}">Назад</a>
</div>
<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Добавление клиента
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

client/templates/client/client_list.html
{% extends 'blogs/base.html'%}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'client:create'%}">Добавить клиента</a>
    <a class="btn btn-outline-primary" href="{% url 'blogs:main'%}">Назад</a>
</div>
{% for object in object_list %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">{{ object }}</p>
            <p class="card-text">{{ object.email }}</p>
            <p class="card-text">{{ object.comment }}</p>
            {% if object.is_active %}
                <p class="card-text">Активен</p>
            {% else %}
                <p class="card-text">Не активен</p>
            {% endif %}

            <p class="card-text">
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    {% if perms.client.view_client %}
                        <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'client:view_client' object.pk %}">Просмотр</a></button>
                    {% endif %}
                    {% if perms.client.change_client %}
                        <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'client:edit' object.pk %}">Редактировать</a></button>
                    {% endif %}
                    {% if perms.client.delete_client %}
                        <button type="button" class="btn btn-sm btn-outline-danger"><a href="{% url 'client:delete' object.pk %}">Удалить</a></button>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}