blogs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from blogs.apps import BlogsConfig
from blogs.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView, main

app_name = BlogsConfig.name

urlpatterns = [
    path('', main, name='main'),
    path('blogs/', BlogListView.as_view(), name='blogs'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from client.apps import ClientConfig
from client.views import ClientListView, ClientCreateView, ClientUpdateView, ClientDetailView, ClientDeleteView

app_name = ClientConfig.name

urlpatterns = [
    path('', cache_page(60)(ClientListView.as_view()), name='client_list'),
    path('create/', ClientCreateView.as_view(), name='create'),
    path('edit/<int:pk>', ClientUpdateView.as_view(), name='edit'),
    path('view/<int:pk>', ClientDetailView.as_view(), name='view_client'),
    path('delete/<int:pk>', ClientDeleteView.as_view(), name='delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls', namespace='blogs')),
    path('users/', include('users.urls', namespace='users')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('client/', include('client.urls', namespace='client'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from mailing.apps import MailingConfig
from mailing.views import MailingListView, MailingDetailView, MailingCreateView, \
    MailingUpdateView, MailingDeleteView


app_name = MailingConfig.name

urlpatterns = [
    path('list/', MailingListView.as_view(), name='list'),
    path('view/<int:pk>', MailingDetailView.as_view(), name='view_mailing'),
    path('create/', MailingCreateView.as_view(), name='create'),
    path('edit/<int:pk>', MailingUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', MailingDeleteView.as_view(), name='delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from users.apps import UsersConfig
from users.services import generate_new_password, verify_view
from users.views import LoginView, LogoutView, RegisterView, ProfileView

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('verifying/', verify_view),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    header = models.CharField(max_length=150, verbose_name='Заголовок')
    content = models.TextField(verbose_name="Содержание")
    image = models.ImageField(upload_to='blogs/', verbose_name='Изображение', **NULLABLE)
    date_create = models.DateField(auto_now_add=True, verbose_name="Дата создания")
    count_views = models.IntegerField(default=0, verbose_name="Количество просмотров")
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано', **NULLABLE)

    def __str__(self):
        return f'{self.header} {self.image}'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blogs/forms.py
from django import forms

from blogs.models import Blog


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('header', 'content', 'image',)

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']

        forbidden_words = ['казино', 'бесплатно', 'вирусы', "кибербуллинг", "приватный", "незаконное", "нарушение",
                           "авторских прав", "финансовые схемы", "обман", "криптовалюта", "биржа", "трейдинг", "дешево",
                           "казино"]

        for forbidden_word in forbidden_words:
            if forbidden_word in cleaned_data.lower():
                raise forms.ValidationError(f'В вашем названии курса есть запретное слово "{forbidden_word.title()}".')

        return cleaned_data

blogs/views.py
import typing

from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blogs.forms import BlogForm
from blogs.models import Blog
from client.models import Client
from mailing.models import Mailing


class BlogCreateView(CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blogs:blogs')

    def form_valid(self, form: typing.Any) -> typing.Any:
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_views += 1
        self.object.save()

        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('header', 'content', 'image',)
    success_url = reverse_lazy('blogs:blogs')


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blogs:blogs')


def main(request):
    client = len(Client.objects.all().distinct('email'))
    blog = Blog.objects.filter(is_published=True).order_by('?')
    mailing = len(Mailing.objects.all())
    mailing_active = len(Mailing.objects.filter(status=2))
    context = {
        'blog': blog[:3],
        'mailing': mailing,
        'mailing_active': mailing_active,
        'client': client
    }
    return render(request, 'blogs/main.html', context)

blogs/templates/blogs/base.html
<!doctype html>
{% load static %}
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.0/examples/album/album.css" rel="stylesheet">

  </head>

  <body>

    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            {% include 'blogs/includes/inc_main_menu.html' %}
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
              <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
              <circle cx="12" cy="13" r="4"></circle>
            </svg>
            <strong>Курсовая работа № 6</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                  aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">{{ title }}</h1>
               <strong><h1>Сайт по рассылкам</h1></strong>
               <a href="/" class="btn btn-outline-primary">Главная</a>
        </div>
      </section>

      <div class="container">
      <div class="row text-start">
        {% block content %}
        {% endblock %}
      </div>
    </main>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>&copy; 2023 - {% now 'Y' %}</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="{% static '/static/js/popper.min.js' %}"></script>
    <script src="{% static '/static/js/bootstrap.min.js' %}"></script>
    <script src="{% static '/static/js/holder.min.js' %}"></script>
  </body>
</html>

blogs/templates/blogs/blog_confirm_delete.html
{% extends 'blogs/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p style="font-size: 25px">Вы действительно хотите удалить блог "{{object|title}}"?</p>
                    <button type="submit" class="btn btn-danger">
                        Подтвердить
                    </button>
                    <a href="{% url 'blogs:blogs' %}" class="btn btn-outline-primary">
                        Отмена
                    </a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blogs/templates/blogs/blog_detail.html
{% extends 'blogs/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="row d-flex justify-content-center text-center">
        <div class="card mx-auto" style="width: 73rem;">
            <img src="{{ blog.image|my_media }}" class="card-img-top" alt="...">
            <div class="card-body">
                <p class="card-text">
                    <span class="blog-title">{{ object.header }}</span>
                </p>
                <hr>
                <p class="card-text">{{ object.content }}</p>
                <div class="card-footer text-right">
                    Блог посмотрели {{object.count_views}} раз
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blogs/templates/blogs/blog_form.html
{% extends 'blogs/base.html' %}
{% block content %}
<div class="col-12 mb-5">
<a class="btn btn-outline-primary" href="{% url 'blogs:main' %}">Назад</a>
</div>
<div class="col-6">
    <div class="card-body">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            {% if object %}
                <a href="{% url 'blogs:view' object.pk %}" type="submit" class="btn btn-success">Сохранить</a>
            {% else %}
                <button type="submit" class="btn btn-success">Создать блог</button>
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

blogs/templates/blogs/blog_list.html
{% extends "blogs/base.html" %}
{% load my_tags %}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'blogs:create' %}">Добавить блог</a>
    <a class="btn btn-outline-primary" href="{% url 'blogs:main' %}">Назад</a>
</div>
{% for object in object_list %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <img class="card-img-top"
                     src="{{ object.image|my_media }}"
                     alt="{{ object.description }}">
        <div class="card-body">
            <h3 class="card-text blog-title">
                {{ object.header }}
            </h3>
            <hr>
            <p class="card-text">
                {{ object.content|truncatechars:150 }}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'blogs:view' object.pk %}" class="btn btn-sm btn-outline-primary">
                        Читать
                    </a>
                    <a href="{% url 'blogs:update' object.pk %}" class="btn btn-sm btn-outline-secondary">
                        Редактировать
                    </a>
                    <a href="{% url 'blogs:delete' object.pk %}" class="btn btn-sm btn-outline-danger">
                        Удалить
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

blogs/templates/blogs/main.html
{% extends 'blogs/base.html'%}
{% block content %}
<div class="col-sm-12 offset-md py">
    <h4 class="text-black">МЕНЮ</h4>
        <div class="col-12 mb-3">

        <a href="{% url 'client:client_list' %}" class="btn btn-outline-primary">Клиенты</a>
        <a href="{% url 'mailing:list' %}" class="btn btn-outline-primary">Рассылки</a>
        <a href="{% url 'blogs:blogs' %}" class="btn btn-outline-primary">Блоги</a>
        {% if user.is_authenticated %}
            <a href="{% url 'users:profile' %}" class="btn btn-outline-primary">Профиль</a>
            <a href="{% url 'users:logout' %}" class="btn btn-outline-primary">Выход</a>
        {% else %}
            <a href="{% url 'users:register' %}" class="btn btn-outline-primary">Регистрация</a>
            <a href="{% url 'users:login' %}" class="btn btn-outline-primary">Войти</a>
        {% endif %}
        </div>
</div>
<p>Количество рассылок: {{ mailing }}</p>
<p>Количество активных рассылок: {{ mailing_active }}</p>
<p>Количество уникальных клиентов для рассылок: {{ client }}</p>
{% for object in blog %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <h3 class="card-text blog-title">
                {{ object.header }}
            </h3>
            <hr>
            <p class="card-text">
                {{ object.content|truncatechars:150 }}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'blogs:view' object.pk %}" class="btn btn-sm btn-outline-primary">
                        Читать
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}